name: Python application

on:
  push:
    branches: [ master ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12' 

            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r Python/requirements.txt

            # - name: Run Tests
            #   run: |
            #     pytest

    docker:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install Docker
              uses : docker/setup-buildx-action@v2   

            - name: Build Docker Image
              run: |
                    docker build -t ${{ secrets.DOCKER_USERNAME }}/github-action-python:${{ github.run_id }} -f Python/Dockerfile Python

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}
            
            - name: Push Docker Image
              uses: docker/build-push-action@v6
              with:
                context: Python
                file: Python/Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/github-action-python:v3
              
    updatek8s:
        runs-on: ubuntu-latest
        needs: [build, docker]

        steps:
        - name: Checkout Code
          uses: actions/checkout@v4
          with: 
            token: ${{ secrets.GITHUBTOKEN }}
        - name: Update tag in k8s deployment
          run: |
            sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/github-action-python:${{ github.run_id }}|" KUBERNETES/deployment.yaml
            

        - name: Git push and commit
          run: |
            git config --global user.email "patildipak0791@gmail.com"
            git config --global user.name "Dipak Patil"
            git add KUBERNETES/deployment.yaml
            git commit -m "[CI]: Update deployment image"
            git push origin HEAD:master -f
      
               
            

                

